/**
 * The order of actions
 *
 * 1. ACTIVATE_FA
 * 2. CHECK_TWO_FACTOR_CODE
 */

export const ACTIVATE_2FA = 'ACTIVATE_2FA'
export const ACTIVATE_2FA_FAILURE = 'ACTIVATE_2FA_FAILURE'
export const ACTIVATE_2FA_SUCCESS = 'ACTIVATE_2FA_SUCCESS'

export const DESACTIVATE_2FA = 'DESACTIVATE_2FA'
export const DESACTIVATE_2FA_FAILURE = 'DESACTIVATE_2FA_FAILURE'
export const DESACTIVATE_2FA_SUCCESS = 'DESACTIVATE_2FA_SUCCESS'

export const CHECK_TWO_FACTOR_CODE = 'CHECK_TWO_FACTOR_CODE'
export const CHECK_TWO_FACTOR_CODE_FAILURE = 'CHECK_TWO_FACTOR_CODE_FAILURE'
export const CHECK_TWO_FACTOR_CODE_SUCCESS = 'CHECK_TWO_FACTOR_CODE_SUCCESS'

export const CANCEL_2FA_ACTIVATION = 'CANCEL_2FA_ACTIVATION'

export const AUTH_MODE = {
  TWO_FA_MAIL: 'two_factor_mail',
  BASIC: 'basic'
}
