export const APPS_DOCTYPE = 'io.cozy.apps'
export const KONNECTORS_DOCTYPE = 'io.cozy.konnectors'
export const REMOTE_REQUEST_DOCTYPES = 'io.cozy.remote.requests'
export const SETTINGS_DOCTYPE = 'io.cozy.settings'
export const OAUTH_CLIENTS_DOCTYPE = 'io.cozy.oauth.clients'
export const FILES_DOCTYPE = 'io.cozy.files'
export const CONTACTS_DOCTYPE = 'io.cozy.contacts'
